# -*- coding: utf-8 -*-
"""fine_tuning_for_code_completion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iv5f93Dqyk0soNcvDd9Bc-kN90sQjSif
"""

!pip install trl bitsandbytes
!pip install -U torchao

import json
import random
import re
import torch
from dataclasses import dataclass
from typing import List, Dict, Any
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments
)
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTConfig, SFTTrainer

# =====================================================================
# 1. ГЛОБАЛЬНАЯ НАСТРАИВАЕМАЯ КОНФИГУРАЦИЯ
# =====================================================================
@dataclass
class TrainingConfig:
    # Пути и модель
    model_name: str = "Qwen/Qwen2.5-Coder-1.5B"
    json_path: str = "train_data_unified_for_completion.json"
    output_dir: str = "./qwen_lora_code_completion"

    # Разделение датасета на уровне файлов
    train_split_ratio: float = 0.95  # 95% на обучение, 5% на валидацию

    # Баланс суффикса в FIM ( Fill-in-the-Middle )
    empty_suffix_ratio: float = 0.50 # 50% примеров будут с пустым суффиксом (конец файла)

    # Распределение стратегий нарезки внутри датасета (должно в сумме давать 1.0)
    group_syntax_ratio: float = 0.50      # Группа А: Синтаксические маркеры
    group_token_healing_ratio: float = 0.25 # Группа Б: Разрезы посреди токенов (Mid-word)
    group_qwen_border_ratio: float = 0.25   # Группа В: Границы токенизатора Qwen
    group_lexical_border_ratio: float = 0.0 # Группа Г: Границы Pascal-лексера

    # Гиперпараметры LoRA
    lora_r: int = 32
    lora_alpha: int = 64
    lora_dropout: float = 0.05

    # Параметры обучения (оптимизировано под Colab T4)
    epochs: int = 3
    batch_size: int = 8
    gradient_accumulation_steps: int = 4
    learning_rate: float = 2e-4
    max_seq_length: int = 512
    prefix_percent_when_cutting = 0.7
    suffix_percent_when_cutting = 0.3

config = TrainingConfig()

# =====================================================================
# 2. ПРОСТЕЙШИЙ ЛЕКСЕР ДЛЯ PASCAL (ДЛЯ ГРУППЫ Г)
# =====================================================================
def get_pascal_lexical_borders(text: str) -> List[int]:
    """Находит индексы символов, которые являются концами токенов Pascal."""
    # Регулярка для поиска слов, чисел и операторов PascalABC.NET
    pattern = r'[a-zA-Z_][a-zA-Z0-9_]*|[0-9]+|:=|<=|>=|<>|[-+*/=<>:;.,()\[\]]'
    borders = []
    for match in re.finditer(pattern, text):
        borders.append(match.end()) # Индекс СРАЗУ ПОСЛЕ завершенного токена языка
    return borders

# =====================================================================
# 3. ГИБРИДНЫЙ СКРИПТ НАРЕЗКИ СЭМПЛОВ В FIM-ШАБЛОН
# =====================================================================
class PascalFimDatasetBuilder:
    def __init__(self, tokenizer, config: TrainingConfig):
        self.tokenizer = tokenizer
        self.cfg = config

        # Токены FIM, зашитые в Qwen-Coder
        self.PREFIX_TOK = "<|fim_prefix|>"
        self.SUFFIX_TOK = "<|fim_suffix|>"
        self.MIDDLE_TOK = "<|fim_middle|>"
        self.EOS_TOK = tokenizer.eos_token or "<|endoftext|>"

    def clean_code(self, code: str) -> str:
      """Мягкая унификация кода.
      Безопасно удаляет комментарии, не трогая текст внутри строк '...'
      """
      # Паттерн находит:
      # 1. Сначала строковые литералы: 'любой текст' (включая экранированные кавычки '')
      # 2. Однострочные комментарии: //...
      # 3. Многострочные комментарии: {...} или (*...*)
      pattern = r"('[^']*')|(//.*?$)|(\{.*?\})|(\(\*.*?\*\))"

      def replacer(match):
          # Если сработала первая группа (match.group(1)), значит мы нашли СТРОКУ.
          # Мы возвращаем её обратно без изменений.
          if match.group(1) is not None:
              return match.group(1)
          # Во всех остальных случаях мы нашли комментарий — заменяем его на пустоту.
          return ""

      # Применяем замену ко всему тексту с флагами MULTILINE (для //) и DOTALL (для { })
      cleaned_code = re.sub(pattern, replacer, code, flags=re.MULTILINE | re.DOTALL)

      # Нормализуем пустые строки
      lines = [line.rstrip() for line in cleaned_code.splitlines() if line.strip()]
      return "\n".join(lines)


    def create_fim_structure(self, prefix: str, suffix: str, middle: str) -> str:
        """Собирает финальную строчку в официальном FIM-формате Qwen."""
        return f"{self.PREFIX_TOK}{prefix}{self.SUFFIX_TOK}{suffix}{self.MIDDLE_TOK}{middle}{self.EOS_TOK}"

    def process_sample(self, raw_code: str) -> List[str]:
        """Нарезает один файл Pascal на несколько FIM примеров по стратегиям."""
        code = self.clean_code(raw_code)
        if len(code) < 20:
            return []

        # -----------------------------------------------------------------
        # 🛡️ ШАГ 1: НАХОДИМ ФИЗИЧЕСКИЕ ИНДЕКСЫ ВСЕХ СТРОК '...' В КОДЕ
        # -----------------------------------------------------------------
        # Сохраняем диапазоны (tuple: start_char_idx, end_char_idx) строковых литералов
        string_ranges = [(m.start(), m.end()) for m in re.finditer(r"'[^']*'", code)]

        def is_inside_string(char_idx: int) -> bool:
            """Проверяет, попадает ли индекс символа внутрь какой-либо строки '...'"""
            for start, end in string_ranges:
                # Если индекс строго между открывающей и закрывающей кавычкой — это запретная зона
                if start < char_idx < end:
                    return True
            return False

        # -----------------------------------------------------------------
        # 📐 ШАГ 2: СБОР МАРКЕРОВ С ФИЛЬТРАЦИЕЙ ЗАПРЕТНЫХ ЗОН
        # -----------------------------------------------------------------

        # Группа А: Синтаксические маркеры
        raw_syntax = [m.end() for m in re.finditer(r'\b(?:begin|var|if|then|do|else|for|foreach|while|new)\b|:=|\.|\b[a-zA-Z_][a-zA-Z0-9_]*\(', code, flags=re.IGNORECASE)]
        syntax_markers = [pos for pos in raw_syntax if not is_inside_string(pos)]

        # Группа Б: Token Healing
        words = [m for m in re.finditer(r'\b[a-zA-Z_][a-zA-Z0-9_]{3,}\b', code)]
        mid_word_borders = []
        for w in words:
            # Если хотя бы начало слова не в строке — проверяем его внутренности
            if not is_inside_string(w.start()):
                # Ставим каретку случайно внутрь слова, гарантируя безопасность
                mid_word_borders.append(random.randint(w.start() + 1, w.end() - 1))

        # Группа В: Границы токенизатора Qwen
        qwen_enc = self.tokenizer.encode(code, add_special_tokens=False)
        qwen_borders = []
        curr_idx = 0
        for t_id in qwen_enc:
            curr_idx += len(self.tokenizer.decode([t_id]))
            # Добавляем границу токена Qwen ТОЛЬКО если она не режет чью-то текстовую строку изнутри
            if not is_inside_string(curr_idx):
                qwen_borders.append(curr_idx)

        # Группа Г: Лексический анализатор Паскаля
        raw_lexical = get_pascal_lexical_borders(code)
        lexical_borders = [pos for pos in raw_lexical if not is_inside_string(pos)]

        # Определяем, будет ли в этом сэмпле пустой суффикс (симуляция конца файла)
        is_empty_suffix = random.random() < self.cfg.empty_suffix_ratio

        # Распределяем, сколько вариантов нарезки сделать на этот файл
        # Пока без lexical
        strategies = ['syntax', 'healing', 'qwen']
        weights = [
            self.cfg.group_syntax_ratio,
            self.cfg.group_token_healing_ratio,
            self.cfg.group_qwen_border_ratio
        ]

        # Сделаем, например, 4 разных разреза на один файл
        chosen_strategies = random.choices(strategies, weights=weights, k=4)

        generated_fims = []

        used_caret_positions = set()

        for strategy in chosen_strategies:
            caret_pos = None

            if strategy == 'syntax' and syntax_markers:
                caret_pos = random.choice(syntax_markers)
            elif strategy == 'healing' and mid_word_borders:
                caret_pos = random.choice(mid_word_borders)
            elif strategy == 'qwen' and qwen_borders:
                caret_pos = random.choice(qwen_borders)
            elif strategy == 'lexical' and lexical_borders:
                caret_pos = random.choice(lexical_borders)

            if caret_pos is None or caret_pos >= len(code) or caret_pos in used_caret_positions:
                continue

            # Разрезаем текст по каретке
            prefix_all = code[:caret_pos]
            remaining = code[caret_pos:]

            middle_line = remaining.split('\n')[0] # Берём строго первую строку после каретки
            if not middle_line.strip():
                # print('Сэмлп не подходит!!!')
                continue

            suffix_all = remaining[len(middle_line):] if not is_empty_suffix else ""

            # -----------------------------------------------------------------
            # 🛡️ УМНАЯ СИНТАКСИЧЕСКАЯ ФИЛЬТРАЦИЯ СЭМПЛА
            # -----------------------------------------------------------------
            # Очищаем сэмпл от пробелов, переносов строк и базовых ключевых слов начала блока
            # Чтобы понять, есть ли в префиксе реальный написанный код
            clean_content = (prefix_all + "\n" + suffix_all).strip()

            # Удаляем из оценки все пустые "каркасные" токены Паскаля (без учета регистра)
            # Убираем ##, var, begin, program, а также точки, запятые и точки с запятой
            clean_content = re.sub(r'(##|var|begin|end|program|const|uses|[;.,\s\n\r])', '', clean_content, flags=re.IGNORECASE)

            # Условие: Если после удаления каркасных слов в префиксе осталось меньше 4 символов,
            # значит пользователь стоит внутри пустого begin-end, пустой секции var или в начале файла.
            # Модели здесь не на что опираться, поэтому сэмпл выбрасываем.
            if len(clean_content) < 4:
                # print('Бесполезный сэмпл!!!!')
                continue
            # -----------------------------------------------------------------

            # --- УМНАЯ ОБРЕЗКА ПОД МАКСИМАЛЬНЫЙ ЛИМИТ (например, 512 или 1024) ---
            # Переводим в токены сырые куски, чтобы точно знать их длину
            pref_ids = self.tokenizer.encode(prefix_all)
            suff_ids = self.tokenizer.encode(suffix_all)
            mid_ids = self.tokenizer.encode(middle_line)

            # Оставляем запас под спецтокены FIM и сам ответ
            max_context_budget = self.cfg.max_seq_length - len(mid_ids) - 10

            # Если мы не влезаем в лимит, пропорционально урезаем контекст вокруг каретки
            if len(pref_ids) + len(suff_ids) > max_context_budget:
                # Префикс оставляем С КОНЦА (код непосредственно ВЫШЕ курсора)
                prefix_all = self.tokenizer.decode(pref_ids[-int(max_context_budget * self.cfg.prefix_percent_when_cutting):])
                # Суффикс оставляем С НАЧАЛА (код непосредственно НИЖЕ курсора)
                if suffix_all:
                    suffix_all = self.tokenizer.decode(suff_ids[:int(max_context_budget * self.cfg.suffix_percent_when_cutting)])

            # Теперь собираем финальный FIM-текст — он гарантированно не превысит max_length
            fim_text = self.create_fim_structure(prefix_all, suffix_all, middle_line)
            used_caret_positions.add(caret_pos)
            generated_fims.append(fim_text)


        return generated_fims

# =====================================================================
# 4. ПОДГОТОВКА ДАННЫХ И ДЕЛЕНИЕ НА TRAIN / VALIDATION
# =====================================================================
def load_and_split_dataset(tokenizer, config: TrainingConfig):
    with open(config.json_path, "r", encoding="utf-8") as f:
        raw_samples = json.load(f)

    # 1. Сначала перемешиваем и делим файлы на уровне КОРНЯ, чтобы избежать утечки данных (Data Leakage)
    random.seed(42)
    random.shuffle(raw_samples)

    split_idx = int(len(raw_samples) * config.train_split_ratio)
    train_files = raw_samples[:split_idx]
    val_files = raw_samples[split_idx:]

    builder = PascalFimDatasetBuilder(tokenizer, config)

    # 2. Нарезаем тренировочную и валидационную выборки по стратегиям
    train_texts = []
    for code in train_files:
        train_texts.extend(builder.process_sample(code))

    val_texts = []
    for code in val_files:
        val_texts.extend(builder.process_sample(code))

    print(f"Исходных программ: {len(raw_samples)}")
    print(f"Получено FIM-сэмплов для Обучения (Train): {len(train_texts)}")
    print(f"Получено FIM-сэмплов для Валидации (Val): {len(val_texts)}")

    train_dataset = Dataset.from_dict({"text": train_texts})
    val_dataset = Dataset.from_dict({"text": val_texts})

    return train_dataset, val_dataset

# =====================================================================
# 5. КАСТОМНЫЙ CALLBACK ДЛЯ РАСЧЕТА LOSS И PERFECT LINES
# =====================================================================
from transformers import TrainerCallback, TrainerControl, TrainingArguments, TrainerState

class CodeCompletionEvalCallback(TrainerCallback):
    """Callback, который на каждой эпохе считает процент идеальных строк (Perfect Lines)."""
    def __init__(self, eval_dataset, tokenizer, num_samples=50):
        self.eval_dataset = eval_dataset
        self.tokenizer = tokenizer
        self.num_samples = min(num_samples, len(eval_dataset))

    def on_evaluate(self, args: TrainingArguments, state: TrainerState, control: TrainerControl, **kwargs):
        model = kwargs['model']
        model.eval()
        perfect_lines_count = 0

        print(f"\nЗапуск генеративной валидации (Perfect Lines) на {self.num_samples} сэмплах...")

        # Извлекаем токены FIM для парсинга
        prefix_tok = "<|fim_prefix|>"
        suffix_tok = "<|fim_suffix|>"
        middle_tok = "<|fim_middle|>"

        for i in range(self.num_samples):
            full_text = self.eval_dataset[i]['text']

            # Находим индексы спецтокенов в сыром тексте
            try:
                p_start = full_text.find(prefix_tok) + len(prefix_tok)
                p_end = full_text.find(suffix_tok)
                s_start = p_end + len(suffix_tok)
                s_end = full_text.find(middle_tok)
                m_start = s_end + len(middle_tok)

                prefix = full_text[p_start:p_end]
                suffix = full_text[s_start:s_end]
                expected_middle = full_text[m_start:].replace(self.tokenizer.eos_token, "").strip()
            except Exception:
                continue

            # Формируем prompt для генерации (модель должна дописать то, что после <fim_middle>)
            prompt = f"{prefix_tok}{prefix}{suffix_tok}{suffix}{middle_tok}"
            inputs = self.tokenizer(prompt, return_tensors="pt").to(model.device)
            with torch.no_grad():
              outputs = model.generate(
                **inputs,
                max_new_tokens=32, # ограничение по генерации !!!
                pad_token_id=self.tokenizer.eos_token_id,
                eos_token_id=self.tokenizer.eos_token_id
            )
            # Декодируем только сгенерированную часть
            generated_text = self.tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:])
            generated_middle = generated_text.replace(self.tokenizer.eos_token, "").strip()
            # Проверяем на идеальное совпадение
            if generated_middle == expected_middle:
              perfect_lines_count += 1

        perfect_lines_ratio = perfect_lines_count / self.num_samples
        print(f">> Эпоха {state.epoch}: Метрика Perfect Lines = {perfect_lines_ratio * 100:.2f}%")

        model.train()

import time
from transformers import TrainerCallback, TrainerControl, TrainingArguments, TrainerState

class SpeedLoggingCallback(TrainerCallback):
    """Callback для принудительного вывода скорости обучения (it/s) каждые N шагов."""
    def __init__(self):
        self.last_time = time.time()
        self.last_step = 0

    def on_log(self, args: TrainingArguments, state: TrainerState, control: TrainerControl, **kwargs):
        # Проверяем, что в логах есть метрики обучения (а не валидации)
        if state.log_history and "loss" in state.log_history[-1]:
            current_time = time.time()
            current_step = state.global_step

            # Считаем разницу во времени и шагах с момента прошлого логирования
            step_diff = current_step - self.last_step
            time_diff = current_time - self.last_time

            if time_diff > 0 and step_diff > 0:
                its = step_diff / time_diff  # итераций (шагов) в секунду
                # Сколько примеров кода обработано в секунду
                examples_per_sec = (step_diff * args.per_device_train_batch_size * args.gradient_accumulation_steps) / time_diff

                # Печатаем скорость прямо в консоль
                print(f"[*] Шаг {current_step}: Скорость = {its:.2f} it/s ({examples_per_sec:.2f} samples/s)")

            # Обновляем таймеры для следующего шага
            self.last_time = current_time
            self.last_step = current_step

# =====================================================================
# 6. ОСНОВНОЙ КОНВЕЙЕР ЗАПУСКА ОБУЧЕНИЯ
# =====================================================================
def start_fine_tuning():
  # 1. Загрузка токенизатора
  tokenizer = AutoTokenizer.from_pretrained(config.model_name, trust_remote_code=True)
  tokenizer.pad_token = tokenizer.eos_token
  # 2. Подготовка датасета
  train_data, val_data = load_and_split_dataset(tokenizer, config)
  # 3. Квантование 4-бит (Для экономии памяти в Colab)
  bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
  )
  # 4. Загрузка модели Qwen Coder
  # print("Загрузка базовой модели в 4-бит...")
  model = AutoModelForCausalLM.from_pretrained(
    config.model_name,
    torch_dtype=torch.float32,
    # quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
  )
  # 5. Настройка LoRA (Компактный конфиг БЕЗ embed_tokens, как в выводах)
  peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=config.lora_r,
    lora_alpha=config.lora_alpha,
    lora_dropout=config.lora_dropout,
    target_modules=[
      "q_proj", "v_proj", "k_proj", "o_proj",
      "gate_proj", "up_proj", "down_proj"
    ] # Эмбеддинги заморожены, экономим память
  )

  total_train_samples = len(train_data)

  steps_per_epoch = total_train_samples // (config.batch_size * config.gradient_accumulation_steps)

  eval_per_epoch_count = 10

  eval_every_steps = steps_per_epoch // eval_per_epoch_count

  print('Валидация каждые', eval_every_steps, 'шагов')

  # 6. Настройка аргументов обучения HF
  sft_config = SFTConfig(
      output_dir=config.output_dir,
      per_device_train_batch_size=config.batch_size,
      per_device_eval_batch_size=config.batch_size,
      gradient_accumulation_steps=config.gradient_accumulation_steps,
      eval_strategy="steps",            # Рассчитываем Loss каждую эпоху
      eval_steps=eval_every_steps,
      logging_strategy="steps",
      logging_steps=1,
      learning_rate=config.learning_rate,
      num_train_epochs=config.epochs,
      bf16=False,
      fp16=False,
      save_strategy="steps",
      save_steps=eval_every_steps,
      report_to="none",
      disable_tqdm=True,
      dataset_text_field="text",
      max_length=config.max_seq_length,
      # lr_scheduler_type="cosine", # Плавное затухание
      # warmup_ratio=0.03,          # Мягкий старт
  )

  # 7. Инициализация SFTTrainer строго по его актуальной сигнатуре
  eval_callback = CodeCompletionEvalCallback(val_data, tokenizer, num_samples=40)
  speed_callback = SpeedLoggingCallback()

  trainer = SFTTrainer(
      model=model,
      args=sft_config,                  # Передаем SFTConfig сюда
      train_dataset=train_data,
      eval_dataset=val_data,
      peft_config=peft_config,
      processing_class=tokenizer,       # Токенизатор теперь передается в этот параметр
      callbacks=[eval_callback, speed_callback]
  )

  # 8. Запуск дообучения!
  print("Старт обучения...")
  trainer.train()

  # 9. Сохранение весов адаптера
  print(f"Обучение завершено. Сохраняю LoRA-адаптер в {config.output_dir}")
  trainer.model.save_pretrained(config.output_dir)

start_fine_tuning()

import sys

# Список только тех библиотек, которые нужны для нашего проекта
target_packages = [
    "transformers", "datasets", "accelerate",
    "peft", "trl", "bitsandbytes", "torchao", "torch"
]

print("--- Версии библиотек в вашем Colab ---")
for package in target_packages:
    try:
        # Динамически импортируем модуль и берем его версию
        module = __import__(package)
        print(f"{package}=={module.__version__}")
    except ImportError:
        print(f"{package} не установлена")
    except AttributeError:
        # У некоторых библиотек (например, bitsandbytes) версия лежит глубоко
        if package == "bitsandbytes":
            import bitsandbytes as bnb
            print(f"bitsandbytes=={bnb.__version__}")
        else:
            print(f"{package}==установлена (версию не удалось определить автоматически)")

print("\nВаша версия Python:", sys.version.split()[0])